'use client';
import {useEffect,useState} from 'react';
import {chapters} from '../deep-study';
type Desk={name:string;date:string;photo:string;notes:string;done:number[]};
const initial:Desk={name:'Imani',date:'2026-10-20',photo:'',notes:'',done:[]};
export default function Desk(){
 const [desk,setDesk]=useState<Desk>(initial);const [ready,setReady]=useState(false);const [message,setMessage]=useState('');
 useEffect(()=>{try{const value=JSON.parse(localStorage.getItem('alive-flight-desk')||'null');if(value&&typeof value==='object')setDesk({name:typeof value.name==='string'?value.name:initial.name,date:typeof value.date==='string'?value.date:initial.date,photo:typeof value.photo==='string'&&value.photo.startsWith('data:image/')?value.photo:'',notes:typeof value.notes==='string'?value.notes:'',done:Array.isArray(value.done)?value.done.filter((n:unknown)=>Number.isInteger(n)&&Number(n)>0&&Number(n)<9):[]});}catch{setMessage('Saved data could not be read. You can still use this desk.');}setReady(true);},[]);
 useEffect(()=>{if(!ready)return;try{localStorage.setItem('alive-flight-desk',JSON.stringify(desk));}catch{setMessage('Your browser could not save this change. Copy your notes before leaving.');}},[desk,ready]);
 return <main className="desk"><a className="text-button" href="/">← Public study guide</a><p className="eyebrow">ALIVE FLIGHT / YOUR PERSONAL SPACE</p><h1>{desk.name || 'Your'}’s <em>flight desk.</em></h1><p>Your photo, your goal, your route to Part 107. Saved in this browser on this device; no account or cloud sync.</p><div className="desk-grid"><section className="desk-card"><div className="photo-area">{desk.photo?<img src={desk.photo} alt="Your chosen flight-desk photo"/>:<span>YOUR NEXT<br/>PERSPECTIVE.<small>Add a photo that reminds you why you fly.</small></span>}</div><label>Personal photo<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>2000000||!['image/jpeg','image/png','image/webp'].includes(file.type)){setMessage('Choose a JPG, PNG or WebP image smaller than 2 MB.');return;}const reader=new FileReader();reader.onload=()=>{setDesk(d=>({...d,photo:String(reader.result)}));setMessage('Photo saved on this device.');};reader.readAsDataURL(file);}}/></label>{desk.photo&&<button onClick={()=>setDesk(d=>({...d,photo:''}))}>Remove photo</button>}<label>Your name<input value={desk.name} maxLength={60} onChange={e=>setDesk({...desk,name:e.target.value})}/></label><label>Target test date<input type="date" value={desk.date} onChange={e=>setDesk({...desk,date:e.target.value})}/></label><p className="small">A planning goal; certificate processing follows the test.</p></section><section className="desk-card"><p className="eyebrow">YOUR STUDY LOG</p><h2>{desk.done.length} of 8 chapters reviewed</h2><progress value={desk.done.length} max={8}/>{chapters.slice(1).map((c,i)=><label className="desk-check" key={c.id}><input type="checkbox" checked={desk.done.includes(i+1)} onChange={e=>setDesk(d=>({...d,done:e.target.checked?[...d.done,i+1]:d.done.filter(n=>n!==i+1)}))}/>{c.label}</label>)}<label>My notes & missed-answer log<textarea rows={9} value={desk.notes} placeholder="Topic → what I missed → why the correct answer works → next review" onChange={e=>setDesk({...desk,notes:e.target.value})}/></label><button onClick={()=>{const a=document.createElement('a');const url=URL.createObjectURL(new Blob([`${desk.name}'s flight desk\nTarget: ${desk.date}\nReviewed: ${desk.done.map(n=>chapters[n].label).join(', ')}\n\n${desk.notes}`],{type:'text/plain'}));a.href=url;a.download='alive-flight-study-notes.txt';a.click();URL.revokeObjectURL(url);}}>Download my notes</button></section></div><p role="status">{message}</p></main>;
}
