import {chapters as base, questions as baseQuestions, sources as original, schedule, type Concept} from './study-data';
export {schedule}; export type {Question} from './study-data';
export const sources=[...original,{id:'supplement',short:'FAA testing supplement',owner:'FAA · CHART WORKBOOK',title:'Actual test figures and chart exercises',url:'https://www.faa.gov/training_testing/testing/supplements',use:'Open FAA-CT-8080-2H for the sport, recreational, private and remote pilot figures. Work the actual charts alongside the sample questions.'},{id:'samples',short:'FAA sample questions',owner:'FAA · ORIGINAL SOURCE',title:'Official UAG sample questions',url:'https://www.faa.gov/sites/faa.gov/files/training_testing/testing/test_questions/uag_questions.pdf',use:'Representative FAA questions with figure references and ACS codes. These are not a promise of the questions on your test.'}];
const extra:Record<number,Concept[]>={
1:[{title:'Worked example: the structure exception',body:'A tower is 250 ft above the ground. Within a 400 ft radius of it, the standard structure exception can allow flight up to 650 ft above that ground level: 250 + 400. Outside that radius, the usual 400 ft AGL limit applies. Terrain changes matter: keep AGL and the immediate uppermost limit of the structure separate.',bullets:['This exception does not override an airspace authorization ceiling.','Check cloud clearance at the higher altitude.','A tall object does not remove the need for VLOS or right of way.'],source:'rules',cite:'§ 107.51(b)'},{title:'Worked example: an accident decision',body:'A drone damages a fence costing $650 to repair. Even if no one is injured, damage to other property exceeds the $500 threshold, so the FAA report is due within 10 calendar days. If only the drone is damaged, this property threshold does not apply. Any loss of consciousness is a separate reporting trigger regardless of the repair bill.',source:'rules',cite:'§ 107.9'}],
2:[{title:'Worked example: MSL meets AGL',body:'Your launch site is at 800 ft MSL. A flight 300 ft above that same terrain is at 1,100 ft MSL. A shelf floor labeled 15 means 1,500 ft MSL, so that point is below the shelf by 400 ft. That calculation alone does not identify the airspace below the shelf. Trace the boundaries and read the legend.',bullets:['MSL = terrain elevation + height AGL.','Use the terrain beneath the aircraft, not just launch elevation, when terrain changes.','A chart obstacle with a parenthesized height shows AGL in parentheses; its top elevation is MSL.'],source:'charts'},{title:'Chart lab: use a real FAA figure',body:'Open the official sample questions and testing supplement. Find Figure 23, area 3, and the Savannah Class C shelf-floor question. Locate the magenta boundary, identify the correct sector, read the lower altitude number, and state its unit before choosing an answer. Next use Figure 22, area 2, to locate the Coeur d’Alene communication frequency requested in the sample.',bullets:['Write down the figure and area before looking for the answer.','Distinguish CTAF, tower, approach and ATIS frequencies; nearby numbers serve different functions.','Explain how the chart supports your choice. This guide does not reproduce the FAA figures.'],source:'samples'}],
3:[{title:'Worked example: clouds impose a lower ceiling',body:'A broken layer is at 800 ft AGL over level terrain. Remaining at least 500 ft below it limits the aircraft to 300 ft AGL, even though the usual altitude limit is 400 ft. The 2,000 ft horizontal cloud clearance also applies. A METAR is a station observation; verify actual conditions at the flight location.',source:'rules',cite:'§ 107.51(c–d)'},{title:'TAF reading workflow',body:'A TAF forecasts conditions around an airport. First find the station, issue time and validity interval. Then read the initial wind, visibility, weather and clouds. FM begins a new prevailing-conditions period; TEMPO describes temporary fluctuations within its interval. Do not treat a future forecast group as a current observation.',bullets:['Use UTC throughout before converting to local time.','Wind direction is the direction it comes from, measured relative to true north in these reports.','The lowest BKN, OVC or vertical-visibility layer establishes a ceiling; FEW and SCT alone do not.','Compare the TAF with current METARs and broader weather trends, then inspect the site.'],source:'weather'},{title:'Weather systems: connect the cause to the hazard',body:'Stable air resists vertical motion and often supports layered clouds, steady precipitation and poor visibility. Unstable air supports rising currents, cumuliform clouds, turbulence and showery precipitation. A temperature inversion is a stable layer that can trap moisture and pollutants. Thunderstorms combine hazards that a low flight altitude does not avoid.',bullets:['Cumulus stage: developing updrafts. Mature stage: precipitation and both updrafts and downdrafts. Dissipating stage: predominantly downdrafts.','A small temperature–dew point spread signals moisture near saturation, not a guarantee of fog.','Look for a trend and an escape plan instead of making a decision from a single number.'],source:'guide'}],
4:[{title:'Worked example: bank and load',body:'For a coordinated, level fixed-wing turn, load factor is 1 / cos(bank angle). At 60 degrees it is 2: a 10 lb aircraft must support an aerodynamic load of about 20 lb. At 30 degrees the factor is about 1.15. Increased load raises the stall speed; a stall occurs at the critical angle of attack, not at one universal airspeed.',source:'guide'},{title:'Payload is a flight-performance change',body:'A payload changes total takeoff weight and may shift the center of gravity. Even below 55 lb, an aircraft can be outside its manufacturer’s limits or have inadequate control and battery margin. Hot, high, humid conditions reduce air density and can further reduce performance.',bullets:['Include batteries, guards, mounts and payload in takeoff weight.','Secure the load and confirm it cannot shift into a propeller or sensor.','Use aircraft-specific operating limits and plan reserve for wind and the return leg.'],source:'guide'}],
5:[{title:'Build a lost-link plan before takeoff',body:'A return-to-home setting is only useful if its route and altitude are safe. Inspect the manufacturer’s lost-link behavior, home-point accuracy, battery triggers and obstacles. Decide where to land if the normal recovery route becomes unsafe. Brief the observer on plain-language calls for traffic, loss of sight and abort.',bullets:['Do not assume a preprogrammed return avoids every obstacle.','Check command-link interference and available battery power before flight.','If another aircraft approaches, yield promptly; do not wait for it to see the drone.'],source:'rules',cite:'§§ 107.37, 107.49'},{title:'Airport radio listening lab',body:'An aircraft reporting left downwind is flying parallel to the landing runway with the runway on its left, usually opposite the landing direction. Base turns toward final; final aligns with the runway. Listening helps build situational awareness, but radio calls do not ensure all traffic is heard and do not grant permission to interfere with airport operations.',bullets:['Use the airport’s published information to identify the relevant frequency.','Sketch runway, downwind, base and final before answering a position question.','Use the FAA sample’s Figure 26 runway-13 traffic-pattern problem as a chart exercise.'],source:'samples'}],
6:[{title:'Scenario: the client says “just one more shot”',body:'You have a narrow battery reserve, increasing wind and a waiting client. In PAVE, the client deadline is an external pressure; the wind belongs to the environment and battery capability to the aircraft. Naming each risk makes the decision clearer: land, change the plan, or reschedule before pressure consumes the remaining margin.',source:'guide'},{title:'Recognize hazardous attitudes in your own words',body:'Anti-authority rejects rules; impulsivity rushes action; invulnerability assumes an accident happens to someone else; macho thinking seeks to prove ability; resignation gives up responsibility. Counter them with respect for rules, deliberate thinking, acceptance of personal risk, conservative judgment and purposeful action.',bullets:['IMSAFE checks illness, medication, stress, alcohol, fatigue and emotion.','A legal minimum does not establish fitness to fly.','Use a predefined abort condition so the decision is made before pressure rises.'],source:'guide'}],
7:[{title:'Category 1 is a combined test',body:'An aircraft weighing 0.55 lb or less must also have no exposed rotating parts that would lacerate human skin to qualify for Category 1 operations over people. Count everything attached, including guards. Weight alone is not enough. Sustained flight over an open-air assembly has additional Remote ID conditions.',source:'rules',cite:'§ 107.110'},{title:'Categories 2, 3 and 4 are not pilot guesses',body:'Categories 2 and 3 involve injury-severity criteria, rotating-part protection, safety-defect requirements, eligibility declarations and labeling. Category 3 adds restrictions, including no operations over open-air assemblies. Category 4 uses an airworthiness certificate and its operating limitations and maintenance requirements. A homemade kinetic-energy calculation does not establish eligibility.',source:'people'},{title:'Night scenario: lights do not replace vision',body:'Night operations require the qualifying knowledge test or training and anti-collision lighting visible for at least 3 statute miles with a flash rate sufficient to avoid collision. Allow eyes time to adapt and avoid staring at one light, which can appear to move through autokinesis. Lighting does not remove the VLOS requirement.',source:'rules',cite:'§§ 107.29, 107.31'}],
8:[{title:'Keep test eligibility and certificate eligibility separate',body:'The FAA testing matrix lists 14 as the minimum age for taking UAG, while a remote pilot certificate requires age 16. For the first-time pilot route, obtain an FAA Tracking Number through IACRA before scheduling the knowledge test. No instructor endorsement is required for this initial test.',source:'matrix'},{title:'After passing: complete the application',body:'Passing the test is not itself a remote pilot certificate. Complete FAA Form 8710-13 through IACRA using the test information; results can take up to 48 hours to become available there. TSA review precedes the temporary certificate. Maintain aeronautical knowledge recency through the applicable training within the preceding 24 calendar months.',source:'certificate'}]
};
export const chapters=base.map((c,i)=>({...c,concepts:[...c.concepts,...(extra[i]||[])]}));

export const questions=[...baseQuestions,...[
 [1,'A tower is 250 ft tall. Within its 400 ft radius, what altitude can the structure exception allow, if all other conditions permit?',['400 ft above the ground','650 ft above the ground at the tower','650 ft above sea level'],1,'250 + 400 = 650 ft above the ground at the tower. Airspace, VLOS and cloud limitations still apply.','rules'],
 [1,'A flight causes $650 of repairable damage to a fence. No one is injured. What is required?',['No report because no one was injured','Report to the FAA within 10 calendar days','Report only if the drone also cost over $500'],1,'Damage to property other than the drone exceeding $500 is a reporting trigger.','rules'],
 [2,'Terrain is 800 ft MSL. The aircraft is 300 ft AGL above it. What is its MSL altitude?',['500 ft','1,100 ft','300 ft'],1,'MSL altitude is terrain elevation plus height above that terrain: 800 + 300 = 1,100.','charts'],
 [2,'A UAS Facility Map shows 100 at your location. What does that mean for permission?',['Automatic authorization to 100 ft','A planning value; obtain the required authorization','Permission whenever the airport is quiet'],1,'A facility-map value does not itself authorize controlled-airspace operations.','authorization'],
 [3,'Broken clouds are at 800 ft AGL. What is the highest altitude maintaining 500 ft below them over level terrain?',['300 ft AGL','400 ft AGL','800 ft AGL'],0,'800 − 500 = 300 ft AGL. Horizontal clearance, visibility and other restrictions also apply.','rules'],
 [3,'Which reported cloud layer establishes a ceiling?',['FEW020','SCT015','BKN030'],2,'The lowest broken, overcast or vertical-visibility layer establishes the ceiling. BKN030 is 3,000 ft AGL.','weather'],
 [3,'In a TAF, what does an FM group do?',['Reports yesterday’s weather','Begins a new prevailing-conditions period','Expresses wind in feet per minute'],1,'FM marks the beginning of a new forecast prevailing-conditions period. Read its UTC time.','weather'],
 [4,'A 10 lb fixed-wing aircraft makes a coordinated, level 60-degree bank turn. Approximate supported load?',['10 lb','15 lb','20 lb'],2,'The load factor is 2 at 60 degrees in a coordinated level turn: 10 × 2 = 20 lb.','guide'],
 [5,'Before relying on return-to-home, what should you check?',['Only the camera settings','Route, altitude, obstacles, home point and aircraft-specific behavior','Nothing; automatic modes ensure separation'],1,'Automation follows its configuration and capabilities. Evaluate recovery behavior and brief alternatives before takeoff.','guide'],
 [6,'A client pressures you to fly with little battery reserve. Which PAVE category contains the deadline pressure?',['Aircraft','External pressures','Environment'],1,'Client deadlines are external pressures. Battery capability is an aircraft concern; consider their combined effect.','guide'],
 [7,'A 0.54 lb drone has exposed propellers that can lacerate skin. Does weight alone qualify it for Category 1?',['Yes','No','Only during daylight'],1,'Category 1 requires both the weight limit and no exposed rotating parts that would lacerate skin. Count all attachments.','rules'],
 [8,'You passed UAG. What is the next certificate step on the first-time-pilot route?',['Begin commercial operations immediately','Apply through IACRA and complete the FAA/TSA process','Wait 24 months'],1,'A passed test is not itself a remote pilot certificate. Complete the application and review process.','certificate']
].map((row,i)=>({id:`deep-${i+1}`,chapter:row[0] as number,prompt:row[1] as string,options:row[2] as string[],answer:row[3] as number,explanation:row[4] as string,source:row[5] as string}))];
