"use client";
import { useEffect, useState, useCallback } from 'react';
import { ArrowLeft, ArrowRight, ArrowUpRight, Check, Compass, BookOpen, Layers, Wind, Scale, Radio, Brain, Moon, BadgeCheck, CalendarDays, Crosshair, RotateCcw } from 'lucide-react';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
import { Progress } from '@/components/ui/progress';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { chapters, questions, sources, schedule, type Question } from './deep-study';

const icons=[Compass,BookOpen,Layers,Wind,Scale,Radio,Brain,Moon,BadgeCheck];
const navigation=[{id:'learn',label:'Study guide',icon:BookOpen},{id:'practice',label:'Practice',icon:Crosshair},{id:'plan',label:'Your flight plan',icon:CalendarDays},{id:'sources',label:'FAA references',icon:ArrowUpRight}];
function SourceLink({id,label}:{id:string;label?:string}){const s=sources.find(s=>s.id===id);return s?<a className="source-link" href={s.url} target="_blank" rel="noreferrer">{label||s.short}<ArrowUpRight size={14} aria-hidden="true"/></a>:null;}

function Metar(){
 const [part,setPart]=useState(2);
 const tokens=[['KBOS','Station','Boston Logan. This identifies where the observation was made.'],['251451Z','Observation time','The 25th at 14:51 UTC. Z means Zulu, or UTC. This sample has no month or year.'],['18012G20KT','Wind','From 180° true at 12 knots, gusting to 20 knots. The gust is 8 knots above the sustained wind.'],['10SM','Visibility','10 statute miles prevailing visibility. Evaluate visibility at your control station too.'],['BKN025','Cloud layer','Broken clouds at 2,500 ft AGL. The lowest broken or overcast layer defines a ceiling; vertical visibility can also define a ceiling.'],['18/14','Temperature / dew point','18°C temperature; 14°C dew point. A narrowing spread can indicate fog or low-cloud potential, given suitable conditions.'],['A3012','Altimeter setting','30.12 inches of mercury. This is a pressure setting, not an altitude.']];
 return <section className="diagram metar"><div className="section-label">DECODE THE REPORT <span>Illustrative · not live weather</span></div><div className="metar-tokens" aria-label="METAR groups">{tokens.map((t,i)=><button key={t[0]} onClick={()=>setPart(i)} className={part===i?'selected':''} aria-pressed={part===i}>{t[0]}</button>)}</div><div className="decode" aria-live="polite"><span>{tokens[part][1]}</span><p>{tokens[part][2]}</p></div><SourceLink id="weather"/></section>;
}
function Airspace(){return <section className="diagram"><div className="section-label">READ THE BOUNDARY <span>Symbol key · not a navigation chart</span></div><div className="airspace-key">{[['B','Solid blue','blue solid'],['C','Solid magenta','magenta solid'],['D','Dashed blue','blue dashed'],['E surface','Dashed magenta','magenta dashed']].map(([a,b,c])=><div key={a}><span className={`boundary ${c}`} aria-hidden="true"/><strong>Class {a}</strong><span>{b}</span></div>)}</div><div className="altitude-example"><span className="chart-fraction"><b>43</b><b>15</b></span><div><h3>Read the altitude in hundreds.</h3><p>This schematic Class B/C label: ceiling 4,300 ft MSL; floor 1,500 ft MSL. Ground at 600 ft MSL + flight at 300 ft AGL = 900 ft MSL, below this shelf. Check the airspace underneath separately.</p></div></div><SourceLink id="charts"/></section>;}
function Limits(){return <section className="limits diagram"><div className="section-label">THE NUMBERS TO KNOW <span>Standard Part 107 limits</span></div><div className="limit-grid">{[['400','ft AGL','Usual altitude ceiling*'],['100','mph','Maximum groundspeed'],['3','statute mi','Minimum flight visibility'],['500 / 2,000','ft','Below / horizontally from clouds']].map(([v,u,l])=><div key={l}><strong>{v}</strong><span>{u}</span><p>{l}</p></div>)}</div><p className="small">*Within a 400 ft radius of a structure, up to 400 ft above its immediate uppermost limit; other restrictions still apply. Certain deviations require a waiver.</p><SourceLink id="rules" label="14 CFR § 107.51"/></section>;}
function LessonVisual({index}:{index:number}){
 if(index===1)return <Limits/>;if(index===2)return <Airspace/>;if(index===3)return <Metar/>;
 if(index===4)return <section className="diagram"><div className="section-label">ONE SYSTEM, CONNECTED EFFECTS</div><div className="performance-grid"><div><span className="eyebrow">CONDITIONS</span><h3>Hot. High. Humid.</h3><p>Lower pressure, heat, or moisture can reduce air density.</p></div><div><span className="eyebrow">RESULT</span><h3>Less performance margin.</h3><p>Use the aircraft’s limits and leave power and battery reserve.</p></div></div><div className="formula"><strong>60° bank → 2× load factor</strong><span>For a coordinated, level fixed-wing turn.</span></div></section>;
 if(index===5)return <div className="operation-strip">{[['Before','Inspect, assess, brief'],['During','Observe, communicate, adapt'],['After','Inspect, record, review']].map(([a,b])=><div key={a}><span>{a}</span><strong>{b}</strong></div>)}</div>;
 if(index===6)return <div className="im-safe diagram"><div className="section-label">CHECK THE PILOT, TOO</div><div>{['Illness','Medication','Stress','Alcohol','Fatigue','Emotion'].map(t=><span key={t}><b>{t[0]}</b>{t}</span>)}</div><p>IMSAFE is a self-assessment before every flight. Being qualified does not always mean being fit to fly today.</p></div>;
 if(index===7)return <div className="night-summary diagram"><Moon size={32}/><div><span className="eyebrow">NIGHT OPERATIONS</span><strong>3 statute miles</strong><p>Anti-collision lighting visible for at least this distance, with a suitable flash rate. Complete the qualifying test or training.</p></div></div>;
 return <div className="certificate-path"><span>01 · Get an FTN</span><span>02 · Pass UAG</span><span>03 · Apply in IACRA</span><span>04 · Review + certificate</span></div>;
}
function QuizCard({q,saved,onAnswer}:{q:Question;saved?:number;onAnswer:(a:number)=>void}){
 const [choice,setChoice]=useState('');const answered=saved!==undefined;
 return <div className="quiz-card"><p className="eyebrow">{chapters[q.chapter].label} · ORIGINAL PRACTICE</p><h2 id={`q-${q.id}`}>{q.prompt}</h2><RadioGroup aria-labelledby={`q-${q.id}`} value={answered?String(saved):choice} onValueChange={setChoice} disabled={answered} className="answer-options">{q.options.map((o,i)=><label key={o} className={`answer-option ${answered&&i===q.answer?'correct':''} ${answered&&saved===i&&i!==q.answer?'incorrect':''}`}><RadioGroupItem id={`${q.id}-${i}`} value={String(i)}/><span className="answer-letter">{String.fromCharCode(65+i)}</span><span>{o}</span>{answered&&i===q.answer&&<Check size={18}/>}</label>)}</RadioGroup>{answered?<div className={`answer-feedback ${saved===q.answer?'right':'wrong'}`} role="status"><strong>{saved===q.answer?'Correct. Here’s why.':'Review this one.'}</strong><p>{q.explanation}</p><SourceLink id={q.source} label={q.cite}/></div>:<Button className="action" disabled={choice===''} onClick={()=>onAnswer(Number(choice))}>Check answer <ArrowRight size={16}/></Button>}</div>;
}

export default function Home(){
 const [view,setView]=useState('learn');const [chapter,setChapter]=useState(0);const [qi,setQi]=useState(0);const [answers,setAnswers]=useState<Record<string,number>>({});const [days,setDays]=useState<number|null>(null);const [storageStatus,setStorageStatus]=useState('Reading position stays on this device.');
 useEffect(()=>{const d=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());setDays(Math.round((Date.parse('2026-10-20T00:00:00Z')-Date.parse(`${d}T00:00:00Z`))/86400000));try{const n=Number(localStorage.getItem('alive-flight-chapter'));if(Number.isInteger(n)&&n>=0&&n<chapters.length)setChapter(n);}catch{setStorageStatus('Reading position is available for this session only.');}},[]);
 const openChapter=useCallback((n:number)=>{setChapter(n);setView('learn');try{localStorage.setItem('alive-flight-chapter',String(n));}catch{setStorageStatus('Reading position is available for this session only.');}window.scrollTo({top:0,behavior:'instant'});},[]);
 function navigate(v:string){setView(v);window.scrollTo({top:0,behavior:'instant'});}
 useEffect(()=>{
  type MC={registerTool:(tool:Record<string,unknown>,options:{signal:AbortSignal})=>void|Promise<void>};const context=(document as Document&{modelContext?:MC}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();
  const tools=[{name:'read_study_guide',description:'Read the visible section, chapter list, and current-session practice results.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({view,chapter:chapters[chapter].label,chapters:chapters.map((c,i)=>({index:i,title:c.label})),practice:{answered:Object.keys(answers).length,correct:questions.filter(q=>answers[q.id]===q.answer).length,total:questions.length}})},{name:'open_study_chapter',description:'Navigate to chapter 0 through 8 and remember its reading position on this device. Does not mark study complete.',inputSchema:{type:'object',properties:{index:{type:'integer',minimum:0,maximum:8}},required:['index'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{const n=(input as {index?:unknown})?.index;if(!Number.isInteger(n)||Number(n)<0||Number(n)>=chapters.length)throw new Error('Choose an index from 0 to 8.');openChapter(Number(n));await new Promise(resolve=>setTimeout(resolve,0));return {opened:chapters[Number(n)].label};}}];
  for(const tool of tools){try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}return()=>lifecycle.abort();
 },[view,chapter,answers,openChapter]);
 const score=questions.filter(q=>answers[q.id]===q.answer).length;const count=Object.keys(answers).length;
 return <div className="app-shell"><a className="skip-link" href="#main">Skip to study content</a><header className="masthead"><a className="brand" href="/" aria-label="Alive Flight home"><span className="brand-icon"><Crosshair size={24} strokeWidth={1.4}/></span><span>ALIVE <b>FLIGHT</b><small>PART 107 STUDY FIELD GUIDE</small></span></a><div className="header-right"><span className="edition">FIELD EDITION / 01</span><a className="pilot" href="/my-flight-desk">My flight desk ↗</a></div></header>
 <Tabs value={view} onValueChange={navigate} className="primary-tabs"><div className="nav-strip"><TabsList className="primary-nav" aria-label="Guide views">{navigation.map(n=><TabsTrigger key={n.id} value={n.id}><n.icon size={16}/><span>{n.label}</span></TabsTrigger>)}</TabsList><span className="target-label"><a href="/my-flight-desk">YOUR PERSONAL FLIGHT DESK ↗</a></span></div><main id="main">
 <TabsContent value="learn"><Tabs value={String(chapter)} onValueChange={v=>openChapter(Number(v))} orientation="vertical" className="study-layout"><aside className="chapter-rail"><div className="rail-label">YOUR STUDY ROUTE <span>09 SECTIONS</span></div><TabsList className="chapter-list" aria-label="Study chapters">{chapters.map((c,i)=>{const Icon=icons[i];return <TabsTrigger value={String(i)} key={c.id}><span className="chapter-number">{i===0?<Compass size={17}/>:String(i).padStart(2,'0')}</span><span>{c.label}</span><Icon className="rail-icon" size={16}/></TabsTrigger>;})}</TabsList><div className="rail-note"><p>ONE CHAPTER AT A TIME.</p><span>Read it. Explain it in your own words. Then put it into practice.</span><small>{storageStatus}</small></div><div className="target-card"><CalendarDays size={20}/><span>BUILD YOUR KNOWLEDGE</span><strong>One chapter at a time.</strong><button onClick={()=>navigate('plan')}>See your study plan <ArrowUpRight size={16}/></button></div></aside><div className="study-main">
 {chapters.map((c,i)=><TabsContent value={String(i)} key={c.id} className="chapter-panel">{i===0?<>
 <div className="intro-heading"><div><p className="eyebrow">PREFLIGHT BRIEFING <span>OPEN TO EVERY PILOT</span></p><h1>Your next perspective.<br/><em>From the sky.</em></h1><p className="intro-copy">A clear path through the knowledge you need for your FAA Remote Pilot Certificate.</p></div><span className="issue-number" aria-hidden="true">107<span>REMOTE PILOT</span></span></div>
 <section className="next-lesson"><div className="next-icon"><BookOpen size={26}/></div><div><p className="eyebrow">YOUR FIRST CHAPTER</p><h2>Rules & responsibilities</h2><p>Who’s in charge, where the limits are, and what makes a flight legal.</p></div><Button className="action" onClick={()=>openChapter(1)}>Start studying <ArrowRight size={17}/></Button></section>
 <div className="intro-grid"><section className="exam-card"><div className="section-label">KNOW THE TEST <span>UAG</span></div><div className="exam-stats"><div><strong>60</strong><span>questions</span></div><div><strong>120</strong><span>minutes</span></div><div><strong>70<small>%</small></strong><span>to pass</span></div></div><p>42 correct out of 60. No instructor endorsement is required for the initial UAG test.</p><SourceLink id="matrix"/></section><section className="focus-card"><p className="eyebrow">YOUR STUDY RHYTHM</p><h2>Learn the reason.<br/>Remember the rule.</h2><p>Try 45–60 minutes a day: read a topic, work a chart or scenario, then explain every missed answer.</p><span className="small">Suggested routine, not an FAA requirement.</span></section></div>
 <section className="blueprint"><div className="section-heading"><h2>What the exam covers</h2><SourceLink id="acs" label="FAA exam blueprint"/></div>{[['Operations','35–45%',45],['Regulations','15–25%',25],['Airspace & requirements','15–25%',25],['Weather','11–16%',16],['Loading & performance','7–11%',11]].map(([label,range,value])=><div className="blueprint-row" key={String(label)}><span>{label}</span><div className="weight-track"><span style={{width:`${Number(value)*2}%`}}/></div><b>{range}</b></div>)}<p className="small">FAA ranges vary by test. This guide groups them into eight practical chapters.</p></section><div className="note"><strong>Study companion, not a complete ground school.</strong><p>Pair this guide with FAA references and real chart exercises. The 36 original practice questions are knowledge checks, not an official FAA question bank or a full mock exam.</p></div>
 </>:<><div className="lesson-heading"><p className="eyebrow">CHAPTER {String(i).padStart(2,'0')} <span>{c.domain}</span></p><h1>{c.title}</h1><p>{c.intro}</p></div><LessonVisual index={i}/><section className="concepts"><div className="section-heading"><h2>The essentials</h2><span>{c.domain}</span></div><Accordion type="multiple" defaultValue={['0','1']}>{c.concepts.map((item,n)=><AccordionItem value={String(n)} key={item.title}><AccordionTrigger><span><b className="concept-number">{String(n+1).padStart(2,'0')}</b>{item.title}</span></AccordionTrigger><AccordionContent><p>{item.body}</p>{item.bullets&&<ul>{item.bullets.map(t=><li key={t}>{t}</li>)}</ul>}<SourceLink id={item.source} label={item.cite}/></AccordionContent></AccordionItem>)}</Accordion></section><div className="trap"><span className="eyebrow">THE EXAM TRAP</span><h3>{c.trapTitle}</h3><p>{c.trap}</p></div><div className="study-task"><Crosshair size={25}/><div><p className="eyebrow">PUT IT INTO PRACTICE</p><p>{c.task}</p><button className="text-button" onClick={()=>{setQi(questions.findIndex(q=>q.chapter===i));navigate('practice');}}>Try this chapter’s questions <ArrowRight size={16}/></button></div></div></>}
 <footer className="chapter-footer"><Button variant="ghost" disabled={i===0} onClick={()=>openChapter(i-1)}><ArrowLeft size={16}/> Back</Button><span>{i+1} / {chapters.length}</span><Button className="action" onClick={()=>i<chapters.length-1?openChapter(i+1):navigate('practice')}>{i===chapters.length-1?'Practice':'Next chapter'}<ArrowRight size={16}/></Button></footer></TabsContent>)}
 </div></Tabs></TabsContent>
 <TabsContent value="practice" className="wide-panel"><div className="page-heading"><p className="eyebrow">KNOWLEDGE CHECK</p><h1>Put your judgment <em>to work.</em></h1><p>36 original questions. Learn from each explanation and revisit the chapter when needed. Results last for this session.</p></div><div className="practice-layout"><section><div className="question-top"><span>QUESTION {String(qi+1).padStart(2,'0')} / {questions.length}</span><button className="text-button" onClick={()=>openChapter(questions[qi].chapter)}>Review chapter <ArrowUpRight size={15}/></button></div><QuizCard key={questions[qi].id} q={questions[qi]} saved={answers[questions[qi].id]} onAnswer={a=>setAnswers(prev=>({...prev,[questions[qi].id]:a}))}/><div className="practice-controls"><Button variant="outline" disabled={qi===0} onClick={()=>setQi(n=>n-1)}><ArrowLeft size={16}/> Previous</Button><Button className="action" onClick={()=>setQi(n=>(n+1)%questions.length)}>{qi===questions.length-1?'Back to question 1':'Next question'}<ArrowRight size={16}/></Button></div></section><aside className="practice-summary"><p className="eyebrow">YOUR SESSION</p><strong className="score">{score}<span> / {count||'—'}</span></strong><p>correct of {count} answered</p><Progress value={count/questions.length*100} aria-label="Practice questions answered"/><span className="small">{count} of {questions.length} attempted</span><div className="question-map" aria-label="Question navigation">{questions.map((q,n)=><button key={q.id} className={`${answers[q.id]!==undefined?(answers[q.id]===q.answer?'right':'wrong'):''} ${qi===n?'current':''}`} aria-label={`Question ${n+1}${answers[q.id]!==undefined?(answers[q.id]===q.answer?', correct':', needs review'):''}`} aria-current={qi===n?'step':undefined} onClick={()=>setQi(n)}>{n+1}</button>)}</div>{count===questions.length&&<div className="completed"><strong>{Math.round(score/questions.length*100)}% on this set</strong><p>Review every miss and use full-length practice with chart figures before judging exam readiness.</p></div>}<Button variant="ghost" className="restart" onClick={()=>{setAnswers({});setQi(0);}} disabled={!count}><RotateCcw size={15}/> Restart practice</Button><p className="small">A learning signal, not a prediction of your FAA exam score.</p></aside></div></TabsContent>
 <TabsContent value="plan" className="wide-panel"><div className="page-heading"><p className="eyebrow">A FLEXIBLE STUDY ROUTE</p><h1>Make room <em>for takeoff.</em></h1><p>Work through this sequence at your own pace. Set your target date and track completed chapters in your personal flight desk. A failed knowledge-test attempt requires a 14-day wait before retesting.</p></div><div className="plan-layout"><section className="schedule">{schedule.map((s,i)=><article key={s.date}><span className="schedule-index">{String(i+1).padStart(2,'0')}</span><div><span className="eyebrow">{`STUDY BLOCK ${i+1}`}</span><h2>{s.title}</h2><p>{s.body}</p>{s.chapter!==undefined&&<button className="text-button" onClick={()=>openChapter(s.chapter!)}>Open chapter <ArrowUpRight size={15}/></button>}</div></article>)}</section><aside className="plan-aside"><span className="eyebrow">BEFORE YOU BOOK</span><h2>Confidence needs evidence.</h2><ul><li>Explain missed answers without memorizing letters.</li><li>Work real sectional and test-supplement figures.</li><li>Try an unfamiliar 60-question practice test in two hours.</li><li>Aim comfortably above 70%, such as 85%+, more than once.</li></ul><span className="small">85% is a suggested study target, not an FAA standard.</span><div className="note"><strong>Passing is one step.</strong><p>The application and TSA review follow the exam. Allow time for certificate processing after the test.</p><SourceLink id="certificate"/></div><SourceLink id="matrix" label="Testing and retest rules"/></aside></div><section className="budget-note"><h2>Keep the study budget low.</h2><p>These FAA and NOAA references are free to read. Paid ground school is optional. Check the current UAG fee and nearby appointments with the FAA’s provider before booking; no price or availability is assumed here.</p><SourceLink id="certificate" label="FAA instructions and testing-provider link"/></section></TabsContent>
 <TabsContent value="sources" className="wide-panel"><div className="page-heading"><p className="eyebrow">THE SOURCE OF TRUTH</p><h1>Go straight <em>to the source.</em></h1><p>Official references behind the guide. Checked September 25, 2026; verify current requirements before your test or a flight.</p></div><div className="note source-note"><strong>Your 2016 FAA study guide is a foundation.</strong><p>It predates later night-operation, operations-over-people, and Remote ID requirements. Use it alongside current regulations, the ACS, and updated FAA guidance.</p></div><div className="resource-list">{sources.map((s,i)=><a href={s.url} key={s.id} target="_blank" rel="noreferrer"><span className="resource-number">{String(i+1).padStart(2,'0')}</span><div><span className="eyebrow">{s.owner}</span><h2>{s.title}</h2><p>{s.use}</p></div><ArrowUpRight size={22}/></a>)}</div><section className="coverage"><h2>How the chapters map to the FAA test</h2><Table><TableHeader><TableRow><TableHead>FAA knowledge area</TableHead><TableHead>Chapters</TableHead><TableHead>Test range</TableHead></TableRow></TableHeader><TableBody>{[['Regulations','01, 07, 08','15–25%'],['Airspace & requirements','02','15–25%'],['Weather','03','11–16%'],['Loading & performance','04','7–11%'],['Operations','05, 06, 07','35–45%']].map(row=><TableRow key={row[0]}>{row.map(t=><TableCell key={t}>{t}</TableCell>)}</TableRow>)}</TableBody></Table><p className="small">Chapter grouping is editorial. Use the ACS for the complete knowledge requirements.</p></section></TabsContent>
 </main></Tabs><footer className="site-footer"><span>ALIVE FLIGHT <b> / </b> A NEW PERSPECTIVE</span><span>Independent study companion · Not affiliated with the FAA</span></footer></div>;
}
